name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Start MinIO
        run: |
          docker run -d \
            --name minio \
            -p 9000:9000 \
            -e MINIO_ROOT_USER=minioadmin \
            -e MINIO_ROOT_PASSWORD=minioadmin \
            minio/minio server /data
          
          # Wait for MinIO to be ready
          timeout 30 bash -c 'until curl -f http://localhost:9000/minio/health/live 2>/dev/null; do sleep 1; done'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests (unit + integration)
        env:
          MINIO_ENDPOINT: localhost
          MINIO_PORT: 9000
          MINIO_USE_SSL: false
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        run: bun test

      - name: Run benchmarks
        env:
          MINIO_ENDPOINT: localhost
          MINIO_PORT: 9000
          MINIO_USE_SSL: false
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        run: bun test tests/benchmarks/

      - name: Run security tests
        env:
          MINIO_ENDPOINT: localhost
          MINIO_PORT: 9000
          MINIO_USE_SSL: false
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        run: bun test tests/security/

      - name: Check test coverage
        env:
          MINIO_ENDPOINT: localhost
          MINIO_PORT: 9000
          MINIO_USE_SSL: false
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
        run: |
          # Run tests with coverage
          bun test --coverage > coverage-output.txt 2>&1 || true
          
          # Extract coverage percentage from bun output
          COVERAGE=$(grep -oP '\d+\.\d+%' coverage-output.txt | head -1 | tr -d '%')
          
          echo "Coverage: ${COVERAGE}%"
          
          # Enforce 90% minimum threshold
          if (( $(echo "$COVERAGE < 90.0" | bc -l) )); then
            echo "❌ Coverage ${COVERAGE}% is below 90% threshold"
            exit 1
          fi
          
          echo "✅ Coverage ${COVERAGE}% meets 90% threshold"

      - name: Cleanup
        if: always()
        run: docker rm -f minio || true
